#python3 main.py -s="London electrician" -t=200 -d="Auto_UK_Elec"
#python3 main.py -s="Milton Keynes electrician" -t=200 -d="Auto_UK_Elec"
#python3 main.py -s="Edinburgh electrician" -t=200 -d="Auto_UK_Elec"
#python3 main.py -s="Belfast electrician" -t=200 -d="Auto_UK_Elec"
#python3 main.py -s="Glasgow electrician" -t=200 -d="Auto_UK_Elec"
python3 main.py -s="Bristol electrician" -t=200 -d="Auto_UK_Elec"
python3 main.py -s="Peterborough electrician" -t=200 -d="Auto_UK_Elec"
python3 main.py -s="Nottingham electrician" -t=200 -d="Auto_UK_Elec"
python3 main.py -s="Leeds electrician" -t=200 -d="Auto_UK_Elec"
python3 main.py -s="Derby electrician" -t=200 -d="Auto_UK_Elec"
python3 main.py -s="Portsmouth electrician" -t=200 -d="Auto_UK_Elec"
python3 main.py -s="Brighton & Hove electrician" -t=200 -d="Auto_UK_Elec"
python3 main.py -s="Oxford electrician" -t=200 -d="Auto_UK_Elec"
#zip -r Auto_UK_Elec.zip out/Auto_UK_Elec

