#zip -r Auto_UK_Elec.zip out/Auto_UK_Elec



python3 main.py -t=200 -d="Auto_UK_Plumber" -s="London"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Birmingham"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Manchester"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Liverpool"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Leeds"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Sheffield"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Bristol"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Coventry"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Leicester"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Nottingham"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Newcastle upon Tyne"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Southampton"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Portsmouth"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Derby"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Stoke-on-Trent"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Sunderland"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Wolverhampton"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Plymouth"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="York"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Oxford"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Cambridge"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Norwich"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Exeter"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Gloucester"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Canterbury"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Bath"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Chester"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Lichfield"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Lincoln"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Worcester"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Ripon"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Carlisle"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Ely"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Durham"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Lancaster"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Newport"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="St Albans"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Salisbury"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Hereford"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Chichester"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Truro"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Wells"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Winchester"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Inverness"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Edinburgh"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Glasgow"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Aberdeen"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Dundee"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Stirling"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Perth"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Belfast"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Lisburn"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Derry"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Armagh"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Swansea"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Cardiff"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Bangor"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="St David's"
python3 main.py -t=200 -d="Auto_UK_Plumber" -s="Llandaff"